In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

In [2]:
df=pd.read_csv("Dataset .csv", encoding='ISO-8859-1')
df

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9546,5915730,NamlÛ± Gurme,208,ï¿½ï¿½stanbul,"Kemankeï¿½ï¿½ Karamustafa Paï¿½ï¿½a Mahallesi,...",Karakï¿½_y,"Karakï¿½_y, ï¿½ï¿½stanbul",28.977392,41.022793,Turkish,...,Turkish Lira(TL),No,No,No,No,3,4.1,Green,Very Good,788
9547,5908749,Ceviz Aï¿½ï¿½acÛ±,208,ï¿½ï¿½stanbul,"Koï¿½ï¿½uyolu Mahallesi, Muhittin ï¿½ï¿½stï¿½_...",Koï¿½ï¿½uyolu,"Koï¿½ï¿½uyolu, ï¿½ï¿½stanbul",29.041297,41.009847,"World Cuisine, Patisserie, Cafe",...,Turkish Lira(TL),No,No,No,No,3,4.2,Green,Very Good,1034
9548,5915807,Huqqa,208,ï¿½ï¿½stanbul,"Kuruï¿½_eï¿½ï¿½me Mahallesi, Muallim Naci Cadd...",Kuruï¿½_eï¿½ï¿½me,"Kuruï¿½_eï¿½ï¿½me, ï¿½ï¿½stanbul",29.034640,41.055817,"Italian, World Cuisine",...,Turkish Lira(TL),No,No,No,No,4,3.7,Yellow,Good,661
9549,5916112,Aï¿½ï¿½ï¿½k Kahve,208,ï¿½ï¿½stanbul,"Kuruï¿½_eï¿½ï¿½me Mahallesi, Muallim Naci Cadd...",Kuruï¿½_eï¿½ï¿½me,"Kuruï¿½_eï¿½ï¿½me, ï¿½ï¿½stanbul",29.036019,41.057979,Restaurant Cafe,...,Turkish Lira(TL),No,No,No,No,4,4.0,Green,Very Good,901
9550,5927402,Walter's Coffee Roastery,208,ï¿½ï¿½stanbul,"Cafeaï¿½ï¿½a Mahallesi, BademaltÛ± Sokak, No 2...",Moda,"Moda, ï¿½ï¿½stanbul",29.026016,40.984776,Cafe,...,Turkish Lira(TL),No,No,No,No,2,4.0,Green,Very Good,591

In [3]:
replacement={
    'ï¿½': 'I',  
    'ï¿½': 'I', 
    'Û±': 'U'
}

In [4]:
def replace_chars(text):
    for wrong, right in replacement.items():
        text = text.replace(wrong, right)
    return text


df = df.applymap(lambda x: replace_chars(x) if isinstance(x, str) else x)


df.tail(10)

C:\Users\user\AppData\Local\Temp\ipykernel_5172\1510248300.py:7: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df = df.applymap(lambda x: replace_chars(x) if isinstance(x, str) else x)

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
9541,5905215,Emirgan SI_tiII,208,IIstanbul,"Emirgan Mahallesi, SakUp SabancU Caddesi, No 4...",EmirgIIn,"EmirgIIn, IIstanbul",29.056620,41.104969,"Restaurant Cafe, Turkish, Desserts",...,Turkish Lira(TL),No,No,No,No,3,4.2,Green,Very Good,877
9542,5926979,Leman KI_ltI_r,208,IIstanbul,"CaferaIIa Mahallesi, NeIIet I_mer Sokak, No 9/...",KadUkI_y Merkez,"KadUkI_y Merkez, IIstanbul",29.022805,40.989705,Restaurant Cafe,...,Turkish Lira(TL),No,No,No,No,3,3.7,Yellow,Good,506
9543,5916085,Dem KarakI_y,208,IIstanbul,"KemankeII Karamustafa PaIIa Mahallesi, Hoca Ta...",KarakI_y,"KarakI_y, IIstanbul",28.978237,41.024633,Cafe,...,Turkish Lira(TL),No,No,No,No,2,4.5,Dark Green,Excellent,761
9544,5915547,KarakI_y GI_llI_oIIlu,208,IIstanbul,"KemankeII Karamustafa PaIIa Mahallesi, RUhtUm ...",KarakI_y,"KarakI_y, IIstanbul",28.977636,41.022904,"Desserts, BI_rek",...,Turkish Lira(TL),No,No,No,No,2,4.7,Dark Green,Excellent,1305
9545,5915054,Baltazar,208,IIstanbul,"KemankeII Karamustafa PaIIa Mahallesi, KUlUI_ ...",KarakI_y,"KarakI_y, IIstanbul",28.981103,41.025785,"Burger, Izgara",...,Turkish Lira(TL),No,No,No,No,3,4.3,Green,Very Good,870
9546,5915730,NamlU Gurme,208,IIstanbul,"KemankeII Karamustafa PaIIa Mahallesi, RUhtUm ...",KarakI_y,"KarakI_y, IIstanbul",28.977392,41.022793,Turkish,...,Turkish Lira(TL),No,No,No,No,3,4.1,Green,Very Good,788
9547,5908749,Ceviz AIIacU,208,IIstanbul,"KoIIuyolu Mahallesi, Muhittin IIstI_ndaII Cadd...",KoIIuyolu,"KoIIuyolu, IIstanbul",29.041297,41.009847,"World Cuisine, Patisserie, Cafe",...,Turkish Lira(TL),No,No,No,No,3,4.2,Green,Very Good,1034
9548,5915807,Huqqa,208,IIstanbul,"KuruI_eIIme Mahallesi, Muallim Naci Caddesi, N...",KuruI_eIIme,"KuruI_eIIme, IIstanbul",29.034640,41.055817,"Italian, World Cuisine",...,Turkish Lira(TL),No,No,No,No,4,3.7,Yellow,Good,661
9549,5916112,AIIIk Kahve,208,IIstanbul,"KuruI_eIIme Mahallesi, Muallim Naci Caddesi, N...",KuruI_eIIme,"KuruI_eIIme, IIstanbul",29.036019,41.057979,Restaurant Cafe,...,Turkish Lira(TL),No,No,No,No,4,4.0,Green,Very Good,901
9550,5927402,Walter's Coffee Roastery,208,IIstanbul,"CafeaIIa Mahallesi, BademaltU Sokak, No 21/B, ...",Moda,"Moda, IIstanbul",29.026016,40.984776,Cafe,...,Turkish Lira(TL),No,No,No,No,2,4.0,Green,Very Good,591

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9551 entries, 0 to 9550
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Restaurant ID         9551 non-null   int64
 1   Restaurant Name       9551 non-null   object
 2   Country Code          9551 non-null   int64
 3   City                  9551 non-null   object
 4   Address               9551 non-null   object
 5   Locality              9551 non-null   object
 6   Locality Verbose      9551 non-null   object
 7   Longitude             9551 non-null   float64
 8   Latitude              9551 non-null   float64
 9   Cuisines              9542 non-null   object
 10  Average Cost for two  9551 non-null   int64
 11  Currency              9551 non-null   object
 12  Has Table booking     9551 non-null   object
 13  Has Online delivery   9551 non-null   object
 14  Is delivering now     9551 non-null   object
 15  Switch to order menu  9551 non-null   object
 16  Price range           9551 non-null   int64
 17  Aggregate rating      9551 non-null   float64
 18  Rating color          9551 non-null   object
 19  Rating text           9551 non-null   object
 20  Votes                 9551 non-null   int64
dtypes: float64(3), int64(5), object(13)
memory usage: 1.5+ MB

In [6]:
df.isna()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9546,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9547,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9548,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9549,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9550,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [7]:
df.isna().sum()

Restaurant ID           0
Restaurant Name         0
Country Code            0
City                    0
Address                 0
Locality                0
Locality Verbose        0
Longitude               0
Latitude                0
Cuisines                9
Average Cost for two    0
Currency                0
Has Table booking       0
Has Online delivery     0
Is delivering now       0
Switch to order menu    0
Price range             0
Aggregate rating        0
Rating color            0
Rating text             0
Votes                   0
dtype: int64

In [8]:
df['Cuisines']

0             French, Japanese, Desserts
1                               Japanese
2       Seafood, Asian, Filipino, Indian
3                        Japanese, Sushi
4                       Japanese, Korean
                      ...
9546                             Turkish
9547     World Cuisine, Patisserie, Cafe
9548              Italian, World Cuisine
9549                     Restaurant Cafe
9550                                Cafe
Name: Cuisines, Length: 9551, dtype: object

In [9]:
mod_value=df['Cuisines'].mode()[0]
df['Cuisines']=df['Cuisines'].fillna(mod_value)

In [10]:
df.isna().sum().sum()

0

In [11]:
df=df.drop(columns=['Country Code','Address','Locality','Locality Verbose','Longitude','Latitude','Average Cost for two','Currency','Currency','Currency','Switch to order menu','Rating color','Rating text','Votes','Has Table booking','Has Online delivery','Is delivering now'])

In [12]:
df

,Restaurant ID,Restaurant Name,City,Cuisines,Price range,Aggregate rating
0,6317637,Le Petit Souffle,Makati City,"French, Japanese, Desserts",3,4.8
1,6304287,Izakaya Kikufuji,Makati City,Japanese,3,4.5
2,6300002,Heat - Edsa Shangri-La,Mandaluyong City,"Seafood, Asian, Filipino, Indian",4,4.4
3,6318506,Ooma,Mandaluyong City,"Japanese, Sushi",4,4.9
4,6314302,Sambo Kojin,Mandaluyong City,"Japanese, Korean",4,4.8
...,...,...,...,...,...,...
9546,5915730,NamlU Gurme,IIstanbul,Turkish,3,4.1
9547,5908749,Ceviz AIIacU,IIstanbul,"World Cuisine, Patisserie, Cafe",3,4.2
9548,5915807,Huqqa,IIstanbul,"Italian, World Cuisine",4,3.7
9549,5916112,AIIIk Kahve,IIstanbul,Restaurant Cafe,4,4.0
9550,5927402,Walter's Coffee Roastery,IIstanbul,Cafe,2,4.0

In [13]:
preferred_cuisines = ['Turkish', 'Seafood, Asian, Filipino, Indian']  # Multiple cuisines
preferred_cities = ['IIstanbul', 'Mandaluyong City']  # Multiple cities
preferred_price_range = 3
min_rating = 4.0

In [14]:
def recommend_restaurants(df, cuisine_preferences, price_range, min_rating, cities):
    # Strip any extra whitespace
    df['City'] = df['City'].str.strip()
    df['Cuisines'] = df['Cuisines'].str.strip()
    
    # Filter based on city, price range, and rating
    filtered_df = df[
        (df['City'].isin(cities)) & 
        (df['Price range'] == price_range) &
        (df['Aggregate rating'] >= min_rating)
    ]
    if cuisine_preferences:
        # Create a regex pattern for multiple cuisines
        pattern = '|'.join(cuisine_preferences)
        filtered_df = filtered_df[filtered_df['Cuisines'].str.contains(pattern, case=False, na=False)]
    
    return filtered_df

In [15]:
recommended_restaurants = recommend_restaurants(df, preferred_cuisines, preferred_price_range, min_rating, preferred_cities)
recommended_restaurants

,Restaurant ID,Restaurant Name,City,Cuisines,Price range,Aggregate rating
9541,5905215,Emirgan SI_tiII,IIstanbul,"Restaurant Cafe, Turkish, Desserts",3,4.2
9546,5915730,NamlU Gurme,IIstanbul,Turkish,3,4.1